services:
    nodeserver:
        build:
            context: ./app
        # ports:
        #     - "81:81"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
